(()=>{
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const stage=$('#stage'), cursor=$('#cursor'), ring=$('#clickRing'), film=$('#rewindFilm'), browser=$('#browser');
  const scrubber=$('#scrubber'), timeEl=$('#time');
  const W={outlook:$('#outlook'),teams:$('#teams'),explorer:$('#explorer'),pdf1:$('#pdf1'),pdf2:$('#pdf2'),qa:$('#qa'),production:$('#production')};
  const END=64;
  let playing=false,startPerf=0,base=0,speed=1,raf=0,topZ=80,lastT=0,lastPortalKey='',lastMailKey='',lastChaosKey='',lastClickIndex=-1;

  const initialMail={
    subject:'New order request — Roll label 60 × 40 mm',
    meta:'Emma Cole <emma@willowandco.example> · Today 9:41 AM',
    body:'<p>Hi Dana,</p><p>We need <b>5,000 roll labels</b> for our sourdough bread line.</p><p>Size: <b>60 × 40 mm</b><br>Needed by: <b>Jun 18</b></p><p>I attached our brief, the current label for reference, and the latest logo. We may need a few text updates before approval.</p>',
    attachments:[['PDF','Willow_Brief.pdf'],['PDF','Current_Label_Reference.pdf'],['PNG','Willow_Logo.png']]
  };
  const revisionMail={
    subject:'Re: New order request — text update',
    meta:'Emma Cole <emma@willowandco.example> · Today 10:03 AM',
    body:'<p>Hi Dana,</p><p>Could you change the text to <b>“No artificial flavors”</b>?</p><p>Also, can you confirm that <b>60 × 40 mm</b> is the final trim size?</p><p>And should the product name read <b>“Sourdough Boule”</b> or <b>“Organic Sourdough”</b>?</p>',
    attachments:[]
  };
  const inviteMail={
    subject:'Re: New order request — review your order',
    meta:'Dana Whitfield <dana@meridian.print> · Today 9:49 AM',
    body:'<p>Hi Emma,</p><p>I’ve created your roll-label order and added the files you sent.</p><p>Please use the secure link below to review the order and continue the collaboration with us.</p><div class="secure-link">🔒 <b>Open order ORD-2482</b><span>collaborative-order.local/o/ORD-2482</span></div><p>We’ll keep the current version, comments and approvals together there.</p>',
    attachments:[]
  };

  function fit(){const s=Math.max(innerWidth/1920,innerHeight/1080);stage.style.transform=`scale(${s})`}
  addEventListener('resize',fit);fit();
  const params=new URLSearchParams(location.search);if(params.get('record')==='1')document.body.classList.add('recording');
  function front(el){if(el)el.style.zIndex=++topZ}
  Object.values(W).forEach(w=>w?.addEventListener('mousedown',()=>front(w)));
  function task(id,on){$('#'+id)?.classList.toggle('active',!!on)}
  function setVisible(name,on){const w=W[name];if(!w)return;w.classList.toggle('visible',!!on);w.classList.remove('hiding');if(on)front(w)}
  function renderMail(m,key){if(lastMailKey===key)return;lastMailKey=key;const a=m.attachments.map(([t,n])=>`<div class="attachment" data-attachment="${n}"><span class="file-badge ${t==='PNG'?'png':''}">${t}</span><div><b>${n}</b><br><small>attached file</small></div></div>`).join('');$('#mailView').innerHTML=`<h1>${m.subject}</h1><div class="mail-meta">${m.meta}</div>${m.body}<div class="attachments">${a}</div>`}
  function ensureMailRows(mode){
    const list=$('#mailList');$('#mail-revision')?.remove();$('#mail-approval')?.remove();
    if(mode==='revision'||mode==='approval'){const d=document.createElement('div');d.id='mail-revision';d.className='mail-item';d.innerHTML='<b>Emma · Willow & Co.</b><span>Re: New order request</span><small>Can you change the text and confirm the size?</small>';list.prepend(d)}
    if(mode==='approval'){const d=document.createElement('div');d.id='mail-approval';d.className='mail-item';d.innerHTML='<b>Emma · Willow & Co.</b><span>Approval question</span><small>Which version should I approve?</small>';list.prepend(d)}
    $$('.mail-item').forEach(x=>x.classList.remove('current','selected'));const sel=mode==='approval'?'#mail-approval':mode==='revision'?'#mail-revision':'[data-mail="initial"]';$(sel)?.classList.add('current','selected')
  }
  function renderChaosFiles(t){
    const rows=[[8,'f-brief','Willow_Brief.pdf','Jun 10, 9:42 AM','1.2 MB',''],[8,'f-ref','Current_Label_Reference.pdf','Jun 10, 9:43 AM','2.1 MB',''],[8,'f-logo','Willow_Logo.png','Jun 10, 9:43 AM','680 KB','png'],[18.5,'f-v2','Willow_Label_v2.pdf','Jun 10, 10:11 AM','2.3 MB',''],[20,'f-v3','Willow_Label_v3.pdf','Jun 10, 10:18 AM','2.3 MB',''],[21,'f-final','Willow_Label_FINAL.pdf','Jun 10, 10:27 AM','2.4 MB',''],[23.3,'f-approved','Willow_Label_FINAL_APPROVED.pdf','Jun 10, 10:34 AM','2.4 MB',''],[24.5,'f-approved2','Willow_Label_FINAL_APPROVED_2.pdf','Jun 10, 10:38 AM','2.4 MB','']];
    const active=t>=24.5?'f-approved2':t>=21?'f-final':t>=10?'f-ref':'';$('#fileList').innerHTML=rows.filter(r=>t>=r[0]).map(r=>`<div id="${r[1]}" class="file-row ${r[1]===active?'selected':''}"><div class="name"><span class="mini-file ${r[5]}"></span>${r[2]}</div><span>${r[3]}</span><span>${r[4]}</span></div>`).join('')
  }
  function renderChaosMessages(t){
    const msgs=[[6,'D','blue','Dana','CSR','New Willow & Co. order: 5,000 roll labels needed by Jun 18. Brief, reference artwork and logo arrived by email.'],[6.4,'N','purple','Nora','Designer','Do we have the final trim size confirmed before I start the artwork?'],[16,'N','purple','Nora','Designer','Updated the copy. Saving a v2 now, but I still need the final product name.'],[17.2,'L','green','Leo','Prepress','I still need confirmed trim size and bleed before I can sign this off.'],[28.5,'M','orange','Maya','Production','If we want to run this today, I need the approved file before noon.'],[30,'R','red','Ryan','Ops Director','What is blocking ORD-2482? Can we release it today?']];
    $('#thread').innerHTML=msgs.filter(m=>t>=m[0]).map(m=>`<div class="thread-msg"><div class="avatar ${m[2]}">${m[1]}</div><div class="msg"><b>${m[3]}</b><small>${m[4]}</small><p>${m[5]}</p></div></div>`).join('')
  }
  function renderPings(t){
    $$('.chaos-ping').forEach(x=>x.remove());const ping=(id,type,title,body,left,top)=>{const d=document.createElement('div');d.id=id;d.className=`chaos-ping ${type} show`;d.style.left=left+'px';d.style.top=top+'px';d.innerHTML=`<b>${title}</b><span>${body}</span>`;stage.appendChild(d)};
    if(t>=25.5)ping('p1','mail','Emma Cole','Which version should I approve?',1415,755);if(t>=28.5)ping('p2','warn','Production','Need approved artwork before noon.',1460,845);if(t>=30)ping('p3','teams','Ryan · Ops Director','Can we release ORD-2482 today?',1340,52)
  }

  function orderSidebar(status='Draft'){return `<aside class="orders"><h2>Orders</h2><div class="order active"><b>Emma Cole</b><span>ORD-2482 &nbsp; Roll label · 60 × 40 mm</span><small>● ${status}</small></div><div class="order"><b>Sam Fenwick</b><span>ORD-2431 &nbsp; Kraft label roll</span><small>● In collaboration</small></div><div class="order"><b>Iris Vogel</b><span>ORD-2435 &nbsp; Folding carton sleeve</span><small>● Preparing print files</small></div></aside>`}
  const summaryAside=`<aside class="order-so-far"><small>Order so far</small><div><b>Customer</b><br>Emma Cole</div><div><b>Product</b><br>Roll label</div><div><b>Needed by</b><br>Jun 18, 2026</div></aside>`;
  function wizardSteps(active){const labels=['Customer','Product','Options','Summary'];return `<div class="wizard-steps">${labels.map((x,i)=>`<div class="wizard-step ${i===active?'active':''} ${i<active?'done':''}"><b>${i+1} &nbsp; ${x}</b><span>${i<active?'Completed':i===active?'In progress':'Not started'}</span></div>`).join('')}</div>`}
  function assetList(){return `<div class="order-assets"><h3>Assets from customer</h3><div><span class="asset-ico pdf">PDF</span><b>Willow_Brief.pdf</b><small>Customer brief</small></div><div><span class="asset-ico pdf">PDF</span><b>Current_Label_Reference.pdf</b><small>Reference only</small></div><div><span class="asset-ico png">PNG</span><b>Willow_Logo.png</b><small>Latest logo</small></div></div>`}
  function renderPortal(key){
    if(lastPortalKey===key)return;lastPortalKey=key;const layout=$('.portal-layout');if(!layout)return;layout.className='portal-layout';
    if(key==='customer'){layout.className='portal-layout wizard-layout';layout.innerHTML=`<div class="portal-wizard"><h1 class="wizard-title">New Order</h1>${wizardSteps(0)}<div class="wizard-card"><div class="wizard-main"><h2>Customer</h2><p>Find an existing customer by name or email.</p><div class="customer-row"><div class="customer-avatar">EC</div><div><b>Emma Cole</b><br><small>emma@willowandco.example</small></div></div></div>${summaryAside}<div class="wizard-actions"><button>Back</button><button class="primary">Continue to product</button></div></div></div>`}
    else if(key==='product'){layout.className='portal-layout wizard-layout';layout.innerHTML=`<div class="portal-wizard"><h1 class="wizard-title">New Order</h1>${wizardSteps(1)}<div class="wizard-card"><div class="wizard-main"><h2>Choose a product</h2><div class="product-grid"><div class="product-card selected"><span class="product-check">✓</span><img src="assets/willow-label-v1.svg"><b>Roll label</b><small>Kraft / BOPP · 20–120 mm</small></div><div class="product-card"><div class="product-placeholder"></div><b>Wraparound label</b><small>Coffee & retail bags</small></div><div class="product-card"><div class="product-placeholder"></div><b>Business card</b><small>350–400 g</small></div><div class="product-card"><div class="product-placeholder"></div><b>Flyer A5 / A4</b><small>115–250 g</small></div></div></div>${summaryAside}<div class="wizard-actions"><button>Back</button><button class="primary">Continue to options</button></div></div></div>`}
    else if(key==='options'){layout.className='portal-layout wizard-layout';layout.innerHTML=`<div class="portal-wizard"><h1 class="wizard-title">New Order</h1>${wizardSteps(2)}<div class="wizard-card"><div class="wizard-main"><h2>Options</h2><div class="option-groups"><div class="option-group"><b>Size</b><div class="option-pills"><span class="option-pill selected">60 × 40 mm</span><span class="option-pill">76 × 51 mm</span><span class="option-pill">100 × 150 mm</span></div></div><div class="option-group"><b>Stock</b><div class="option-pills"><span class="option-pill selected">Kraft uncoated</span><span class="option-pill">White BOPP</span></div></div><div class="option-group"><b>Finish</b><div class="option-pills"><span class="option-pill selected">None</span><span class="option-pill">Matte lamination</span></div></div><div class="option-group"><b>Quantity</b><div class="option-pills"><span class="option-pill">1,000 pcs</span><span class="option-pill selected">5,000 pcs</span><span class="option-pill">10,000 pcs</span></div></div><div class="variant-preview"><div><b>PRODUCT VARIANT</b><p>60 × 40 mm · Kraft uncoated · No finish · Permanent adhesive · Outside wound · 40 mm core</p><small>SKU RL-6040-KRAFT-NF-5000</small></div><img src="assets/willow-label-v1.svg"></div></div></div>${summaryAside}<div class="wizard-actions"><button>Back</button><button class="primary">Continue to summary</button></div></div></div>`}
    else if(key==='summary'){layout.className='portal-layout wizard-layout';layout.innerHTML=`<div class="portal-wizard"><h1 class="wizard-title">New Order</h1>${wizardSteps(3)}<div class="wizard-card"><div class="wizard-main"><h2>Summary</h2><div class="summary-grid"><div><span>Customer</span><b>Emma Cole</b></div><div><span>Email</span><b>emma@willowandco.example</b></div><div><span>Product</span><b>Roll label</b></div><div><span>SKU</span><b>RL-6040-KRAFT-NF-5000</b></div><div><span>Variant</span><b>60 × 40 mm · Kraft uncoated</b></div><div><span>Quantity</span><b>5,000 pcs</b></div></div><div class="incoming-assets-summary"><b>Customer files</b><span>3 assets will be attached to the order</span></div></div>${summaryAside}<div class="wizard-actions"><button>Back</button><button class="primary">Create order as Draft</button></div></div></div>`}
    else if(key==='draft-assets'){layout.className='portal-layout order-screen-relief';layout.innerHTML=`${orderSidebar('Draft')}<main class="order-main"><div class="order-title"><span>ORD-2482</span><h1>Roll label · 60 × 40 mm</h1><small>Draft &nbsp; Emma Cole &nbsp; Due Jun 18, 2026</small></div><div class="order-timeline"><span>Order created · Just now</span>${assetList()}<article class="no-version"><b>Design</b><small>No version yet. Customer source files are attached and ready for the team.</small></article></div><div class="reply">Public reply · customer sees it<div>Reply to the customer…</div></div></main><aside class="next-action"><h3>Next action</h3><div class="action-card"><b>YOUR MOVE</b><p>Customer assets are in the order. Prepare the initial version when ready.</p><button>Prepare initial version</button></div><h3>Current design</h3><div class="empty-design">No version yet</div></aside>`}
    else if(key==='customer-wait'){layout.className='portal-layout customer-facing';layout.innerHTML=`<div class="customer-shell"><header><b>Meridian.</b><span>Print &amp; Packaging</span><nav>My orders &nbsp; 🔒 Secure session &nbsp; <b>EC</b></nav></header><main><div class="customer-order-head"><small>ORD-2482 · Roll label</small><h1>Roll label · 60 × 40 mm</h1><div class="customer-progress"><b>● Review & collaborate</b><span>○ Confirm order</span><span>○ In production</span></div></div><div class="customer-wait-card"><h2>We received your order</h2><p>Your brief, reference label and logo are safely attached to this order.</p><div class="customer-assets"><span>Willow_Brief.pdf</span><span>Current_Label_Reference.pdf</span><span>Willow_Logo.png</span></div><b>Meridian is preparing the first design version.</b></div></main></div>`}
    else if(key==='internal-v1'){layout.className='portal-layout order-screen-relief';layout.innerHTML=`${orderSidebar('Waiting on the customer')}<main class="order-main"><div class="order-title"><span>ORD-2482</span><h1>Roll label · 60 × 40 mm</h1><small>Waiting on the customer &nbsp; Emma Cole &nbsp; Due Jun 18, 2026</small></div><div class="order-timeline"><span>Order created</span>${assetList()}<article class="version-card"><img src="assets/willow-label-v1.svg"><div><b>Version 1 published</b><small>Initial version · saved from the editor</small><p>The original customer assets remain attached to the order.</p></div></article></div><div class="reply">Public reply · customer sees it<div>Version 1 is ready for review.</div></div></main><aside class="next-action"><h3>Next action</h3><div class="action-card"><b>YOUR MOVE</b><p>Version 1 is ready. Emma can review it from the same order link.</p><button>View customer session</button></div><h3>Current design</h3><img src="assets/willow-label-v1.svg"></aside>`}
    else if(key==='customer-v1'){layout.className='portal-layout customer-facing';layout.innerHTML=`<div class="customer-shell"><header><b>Meridian.</b><span>Print &amp; Packaging</span><nav>My orders &nbsp; 🔒 Secure session &nbsp; <b>EC</b></nav></header><main><div class="customer-order-head"><small>ORD-2482 · Roll label</small><h1>Roll label · 60 × 40 mm</h1><div class="customer-progress"><b>● Review & collaborate</b><span>○ Confirm order</span><span>○ In production</span></div></div><div class="customer-grid"><section class="proof-card"><header><b>Version 1</b><small>Latest</small></header><img src="assets/willow-label-v1.svg"><button>Open in Editor</button></section><section class="conversation"><h2>Conversation</h2><div class="conversation-msg"><b>Dana Whitfield</b><small>Meridian · Just now</small><p>Initial version published. Please review it here; comments and every next version will stay with this order.</p></div><textarea placeholder="Write a message to Meridian"></textarea><button>Send</button></section></div></main></div>`}
  }
  function showBrowser(on,key){browser.classList.toggle('visible',!!on);task('tbBrowser',!!on);if(on)renderPortal(key)}
  function showOutlook(on,mailMode='initial'){
    setVisible('outlook',on);task('tbOutlook',on);if(!on)return;
    if(mailMode==='revision'){ensureMailRows('revision');renderMail(revisionMail,'revision')}else if(mailMode==='approval'){ensureMailRows('approval');renderMail(revisionMail,'approval')}else if(mailMode==='invite'){ensureMailRows('initial');renderMail(inviteMail,'invite')}else{ensureMailRows('initial');renderMail(initialMail,'initial')}
  }
  function renderChaos(t){
    const key=[t>=30,t>=28.5,t>=27,t>=25.5,t>=24.5,t>=23.3,t>=22,t>=21,t>=20,t>=18.5,t>=17.2,t>=16,t>=13,t>=10,t>=8,t>=6,t>=2].join('');if(lastChaosKey===key)return;lastChaosKey=key;
    showBrowser(false,'');showOutlook(t>=2,t>=25.5?'approval':t>=13?'revision':'initial');setVisible('teams',t>=6);task('tbTeams',t>=6);setVisible('explorer',t>=8);task('tbExplorer',t>=8);setVisible('pdf1',t>=10);setVisible('pdf2',t>=22);task('tbPdf',t>=10);setVisible('qa',t>=27);setVisible('production',t>=28.5);renderChaosFiles(t);renderChaosMessages(t);renderPings(t);stage.classList.toggle('climax-hold',t>=30)
  }
  function cleanDesktop(){lastChaosKey='';lastPortalKey='';Object.keys(W).forEach(n=>setVisible(n,false));$$('.task-icon').forEach(x=>x.classList.remove('active'));$$('.chaos-ping').forEach(x=>x.remove());stage.classList.remove('climax-hold')}
  const cursorKeys=[[0,1710,980],[2,820,280],[5.5,760,430],[8.8,440,776],[10.1,440,810],[13.6,760,250],[18.8,455,875],[22.2,1290,650],[25.8,770,190],[30.5,1510,185],[36,1710,980],[38,760,270],[39.2,1110,1015],[41,1150,755],[43,915,420],[45,890,400],[47,1320,820],[49,1420,330],[52,770,210],[54,870,555],[55.5,1170,1015],[58.5,1470,325],[61,1260,720],[64,1640,850]];
  function cursorPosition(t){let a=cursorKeys[0],b=cursorKeys[cursorKeys.length-1];for(let i=0;i<cursorKeys.length-1;i++){if(t>=cursorKeys[i][0]&&t<=cursorKeys[i+1][0]){a=cursorKeys[i];b=cursorKeys[i+1];break}}const p=Math.max(0,Math.min(1,(t-a[0])/Math.max(.001,b[0]-a[0])));return[a[1]+(b[1]-a[1])*p,a[2]+(b[2]-a[2])*p]}
  function cursorAt(t){const [x,y]=cursorPosition(t);cursor.style.opacity=t>.8?1:0;cursor.style.transform=`translate3d(${x}px,${y}px,0)`}
  const clicks=[8.9,10.2,13.7,18.9,22.3,25.9,39.25,41.1,43.1,45.1,47.2,49.2,54.1,55.6,58.7,61.1];
  function maybeClicks(prev,t){if(!playing||t<prev)return;clicks.forEach((ct,i)=>{if(prev<ct&&t>=ct&&i!==lastClickIndex){lastClickIndex=i;const [x,y]=cursorPosition(ct);pulseClick(x,y)}})}
  function pulseClick(x,y){ring.classList.remove('go');void ring.offsetWidth;ring.style.left=x+'px';ring.style.top=y+'px';ring.classList.add('go');cursor.classList.remove('press');void cursor.offsetWidth;cursor.classList.add('press');setTimeout(()=>cursor.classList.remove('press'),220)}
  function renderAt(rawT){
    const t=Math.max(0,Math.min(END,rawT));stage.classList.remove('rewinding');film.classList.remove('on');
    if(t<33)renderChaos(t);else if(t<36){const reverseT=30*(1-(t-33)/3);renderChaos(Math.max(0,reverseT));stage.classList.add('rewinding');film.classList.add('on')}else{cleanDesktop();if(t<39){showOutlook(true,'initial');showBrowser(false,'')}else if(t<41){showOutlook(true,'initial');showBrowser(true,'customer')}else if(t<43){showOutlook(false);showBrowser(true,'customer')}else if(t<45){showOutlook(false);showBrowser(true,'product')}else if(t<47){showOutlook(false);showBrowser(true,'options')}else if(t<49){showOutlook(false);showBrowser(true,'summary')}else if(t<52){showOutlook(false);showBrowser(true,'draft-assets')}else if(t<55){showBrowser(false,'');showOutlook(true,'invite')}else if(t<58){showOutlook(false);showBrowser(true,'customer-wait')}else if(t<60.5){showOutlook(false);showBrowser(true,'internal-v1')}else{showOutlook(false);showBrowser(true,'customer-v1')}}
    cursorAt(t);maybeClicks(lastT,t);lastT=t;timeEl.textContent=`${t.toFixed(1)} / ${END.toFixed(1)}`;scrubber.value=Math.round(t*100)
  }
  function play(){if(playing)return;playing=true;startPerf=performance.now();lastT=base;raf=requestAnimationFrame(tick)}
  function pause(){if(!playing)return;base=Math.min(END,base+(performance.now()-startPerf)/1000*speed);playing=false;cancelAnimationFrame(raf);renderAt(base)}
  function tick(now){if(!playing)return;const t=base+(now-startPerf)/1000*speed;renderAt(t);if(t>=END){base=END;playing=false;return}raf=requestAnimationFrame(tick)}
  function seek(t){playing=false;cancelAnimationFrame(raf);base=Math.max(0,Math.min(END,t));lastT=base;lastClickIndex=-1;renderAt(base)}
  function restart(){seek(0);play()}
  scrubber.max=END*100;scrubber.value=0;scrubber.addEventListener('input',()=>seek(Number(scrubber.value)/100));$('#play').onclick=play;$('#pause').onclick=pause;$('#restart').onclick=restart;$('#speed').onclick=()=>{speed=speed===1?1.5:speed===1.5?.75:1;$('#speed').textContent=speed+'×'};$$('[data-snap]').forEach(b=>b.onclick=()=>{const map={clean:0,initial:3,peak:31,product:49};seek(map[b.dataset.snap]??0)});addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();playing?pause():play()}if(e.key.toLowerCase()==='r')restart();if(e.key==='ArrowRight')seek(base+1);if(e.key==='ArrowLeft')seek(base-1)});
  renderMail(initialMail,'initial');renderAt(0);if(params.get('autoplay')==='1'||params.get('record')==='1')setTimeout(play,350)
})();
