(()=>{
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const stage=$('#stage'), cursor=$('#cursor'), ring=$('#clickRing'), film=$('#rewindFilm'), browser=$('#browser');
  const scrubber=$('#scrubber'), timeEl=$('#time');
  const W={outlook:$('#outlook'),explorer:$('#explorer'),pdf1:$('#pdf1'),pdf2:$('#pdf2'),qa:$('#qa'),production:$('#production'),designer:$('#designerChat'),prepress:$('#prepressChat'),director:$('#directorChat')};
  const END=86;
  let playing=false,startPerf=0,base=0,speed=1,raf=0,topZ=80,lastT=0;
  let lastMailKey='',lastFilesKey='',lastPortalKey='',lastChatKey='',lastPingKey='';
  let cursorAnim=null,cursorHideTimer=0;
  const firedActions=new Set();
  const params=new URLSearchParams(location.search); if(params.get('record')==='1')document.body.classList.add('recording');

  const initialMail={subject:'New order request — Roll label 60 × 40 mm',meta:'Emma Cole <emma@willowandco.example> · Today 9:41 AM',body:'<p>Hi Dana,</p><p>We need <b>5,000 roll labels</b> for our sourdough bread line.</p><p>Size: <b>60 × 40 mm</b><br>Needed by: <b>Jun 18</b></p><p>I attached our brief, the current label for reference, and the latest logo. We may need a few text updates before approval.</p>',attachments:[['PDF','Willow_Brief.pdf'],['PDF','Current_Label_Reference.pdf'],['PNG','Willow_Logo.png']]};
  const revisionMail={subject:'Re: New order request — text update',meta:'Emma Cole <emma@willowandco.example> · Today 10:03 AM',body:'<p>Hi Dana,</p><p>Could you change the text to <b>“No artificial flavors”</b>?</p><p>Also, can you confirm that <b>60 × 40 mm</b> is the final trim size?</p><p>And should the product name read <b>“Sourdough Boule”</b> or <b>“Organic Sourdough”</b>?</p>',attachments:[]};

  function fit(){const s=Math.max(innerWidth/1920,innerHeight/1080);stage.style.transform=`scale(${s})`} addEventListener('resize',fit);fit();
  function front(el){if(el)el.style.zIndex=++topZ} Object.values(W).forEach(w=>w?.addEventListener('mousedown',()=>front(w)));
  function task(id,on){$('#'+id)?.classList.toggle('active',!!on)}
  function setVisible(name,on){const w=W[name];if(!w)return;const was=w.classList.contains('visible');w.classList.toggle('visible',!!on);w.classList.remove('hiding');if(on&&!was)front(w)}
  function hideAllWindows(){Object.keys(W).forEach(k=>setVisible(k,false));$$('.task-icon').forEach(x=>x.classList.remove('active'))}
  function showBrowser(on){const was=browser.classList.contains('visible');browser.classList.toggle('visible',!!on);task('tbBrowser',!!on);if(on&&!was)browser.style.zIndex=++topZ}

  function renderMail(m,key){if(lastMailKey===key)return;lastMailKey=key;const a=m.attachments.map(([t,n])=>`<div class="attachment" data-attachment="${n}"><span class="file-badge ${t==='PNG'?'png':''}">${t}</span><div><b>${n}</b><br><small>attached file</small></div></div>`).join('');$('#mailView').innerHTML=`<h1>${m.subject}</h1><div class="mail-meta">${m.meta}</div>${m.body}<div class="attachments">${a}</div>`}
  function ensureMailRows(mode){const list=$('#mailList');$('#mail-revision')?.remove();$('#mail-approval')?.remove();if(mode==='revision'||mode==='approval'){const d=document.createElement('div');d.id='mail-revision';d.className='mail-item';d.innerHTML='<b>Emma · Willow & Co.</b><span>Re: New order request</span><small>Can you change the text and confirm the size?</small>';list.prepend(d)}if(mode==='approval'){const d=document.createElement('div');d.id='mail-approval';d.className='mail-item';d.innerHTML='<b>Emma · Willow & Co.</b><span>Approval question</span><small>Which version should I approve?</small>';list.prepend(d)}$$('.mail-item').forEach(x=>x.classList.remove('current','selected'));const sel=mode==='approval'?'#mail-approval':mode==='revision'?'#mail-revision':'[data-mail="initial"]';$(sel)?.classList.add('current','selected')}
  function renderReplyReady(){const key='reply-ready';if(lastMailKey===key)return;lastMailKey=key;ensureMailRows('initial');$('#mailView').innerHTML=`<h1>${initialMail.subject}</h1><div class="mail-meta">${initialMail.meta}</div>${initialMail.body}<div class="attachments">${initialMail.attachments.map(([t,n])=>`<div class="attachment"><span class="file-badge ${t==='PNG'?'png':''}">${t}</span><div><b>${n}</b><br><small>attached file</small></div></div>`).join('')}</div><button class="mail-reply-button" id="replyButton">↩ Reply</button>`}
  function renderReplyComposer(pasted=false,sent=false){const key=`reply-${pasted}-${sent}`;if(lastMailKey===key)return;lastMailKey=key;ensureMailRows('initial');$('#mailView').innerHTML=`<div class="compose-head"><b>Reply to Emma Cole</b><span>emma@willowandco.example</span></div><div class="compose-body"><p>Hi Emma,</p><p>I’ve created your roll-label order and added the files you sent.</p><p>Please use the secure link below to review the order and continue the collaboration with us.</p><div class="paste-zone ${pasted?'has-link':''}" id="clientPasteZone">${pasted?'<div class="secure-link"><span>🔒</span><div><b>Open order ORD-2482</b><small>collaborative-order.local/o/ORD-2482</small></div></div>':'<span class="caret-line">Paste secure order link here…</span>'}</div><p>We’ll keep versions, comments and approvals together there.</p><p>Best,<br>Dana</p></div><div class="compose-actions"><button id="sendReply" class="send-reply">${sent?'✓ Sent':'Send'}</button></div>`}

  function renderChaosFiles(t){const rows=[[8,'f-brief','Willow_Brief.pdf','Jun 10, 9:42 AM','1.2 MB',''],[8,'f-ref','Current_Label_Reference.pdf','Jun 10, 9:43 AM','2.1 MB',''],[8,'f-logo','Willow_Logo.png','Jun 10, 9:43 AM','680 KB','png'],[18.5,'f-v2','Willow_Label_v2.pdf','Jun 10, 10:11 AM','2.3 MB',''],[20,'f-v3','Willow_Label_v3.pdf','Jun 10, 10:18 AM','2.3 MB',''],[21,'f-final','Willow_Label_FINAL.pdf','Jun 10, 10:27 AM','2.4 MB',''],[23.3,'f-approved','Willow_Label_FINAL_APPROVED.pdf','Jun 10, 10:34 AM','2.4 MB',''],[24.5,'f-approved2','Willow_Label_FINAL_APPROVED_2.pdf','Jun 10, 10:38 AM','2.4 MB','']];const active=t>=24.5?'f-approved2':t>=21?'f-final':t>=10?'f-ref':'';const visible=rows.filter(r=>t>=r[0]);const key=visible.map(r=>r[1]).join('|')+'@'+active;if(lastFilesKey===key)return;lastFilesKey=key;$('#fileList').innerHTML=visible.map(r=>`<div id="${r[1]}" class="file-row ${r[1]===active?'selected':''}"><div class="name"><span class="mini-file ${r[5]}"></span>${r[2]}</div><span>${r[3]}</span><span>${r[4]}</span></div>`).join('')}
  function chatMessage(side,name,role,text){return `<div class="staff-msg ${side}"><div><b>${name}</b><small>${role}</small><p>${text}</p></div></div>`}
  function renderStaffChats(t){const designer=t<6?'off':t<15?'start':t<24?'update':'late';const prepress=t<17?'off':t<24?'start':'late';const director=t<30?'off':'start';const key=[designer,prepress,director].join('|');if(lastChatKey===key)return;lastChatKey=key;if(designer!=='off'){$('#designerThread').innerHTML=chatMessage('me','Dana','CSR','New Willow order. Brief, reference label and logo are in the job folder. Need 5,000 labels by Jun 18.')+chatMessage('them','Nora','Designer','Got it. Is 60 × 40 mm the final trim size or the finished size?')+(designer!=='start'?chatMessage('them','Nora','Designer','I updated the copy and saved v2, but I still need the final product name.'):'')+(designer==='late'?chatMessage('me','Dana','CSR','Client says “No artificial flavors”. Still waiting on whether the name is Sourdough Boule or Organic Sourdough.'):'')}if(prepress!=='off'){$('#prepressThread').innerHTML=chatMessage('me','Dana','CSR','Can you sanity-check trim and bleed before we release this?')+chatMessage('them','Leo','Prepress','I need the confirmed trim size and 3 mm bleed. Also, which PDF is current?')+(prepress==='late'?chatMessage('them','Leo','Prepress','I now see FINAL_APPROVED and FINAL_APPROVED_2. They do not match, so I can’t sign this off yet.'):'')}if(director!=='off'){$('#directorThread').innerHTML=chatMessage('them','Ryan','Ops Director','What is blocking ORD-2482? Can we release it today?')+chatMessage('me','Dana','CSR','Waiting on final wording and trying to establish which artwork file is actually approved.')}}
  function renderPings(t){const key=t>=28.5?'two':t>=25.5?'one':'none';if(lastPingKey===key)return;lastPingKey=key;$$('.chaos-ping').forEach(x=>x.remove());const ping=(id,type,title,body,left,top)=>{const d=document.createElement('div');d.id=id;d.className=`chaos-ping ${type} show`;d.style.left=left+'px';d.style.top=top+'px';d.innerHTML=`<b>${title}</b><span>${body}</span>`;stage.appendChild(d)};if(t>=25.5)ping('p1','mail','Emma Cole','Which version should I approve?',1410,748);if(t>=28.5)ping('p2','warn','Production','Need approved artwork before noon.',1440,826)}

  function wizardSteps(active){const labels=['Customer','Product','Options','Summary'];return `<div class="wizard-steps">${labels.map((x,i)=>`<div class="wizard-step ${i===active?'active':''} ${i<active?'done':''}"><b>${i+1} &nbsp; ${x}</b><span>${i<active?'Completed':i===active?'In progress':'Not started'}</span></div>`).join('')}</div>`}
  const summaryAside=`<aside class="order-so-far"><small>Order so far</small><div><b>Customer</b><br>Emma Cole</div><div><b>Product</b><br>Roll label</div><div><b>Needed by</b><br>Jun 18, 2026</div></aside>`;
  function sourceAssets(){return `<div class="order-assets"><h3>Assets from customer</h3><div><span class="asset-ico pdf">PDF</span><b>Willow_Brief.pdf</b><small>Customer brief</small></div><div><span class="asset-ico pdf">PDF</span><b>Current_Label_Reference.pdf</b><small>Reference only</small></div><div><span class="asset-ico png">PNG</span><b>Willow_Logo.png</b><small>Latest logo</small></div></div>`}
  function portalShell(title,body){return `<main class="v10-order-main"><div class="v10-order-head"><small>ORD-2482 · Willow &amp; Co.</small><h1>${title}</h1><span>Roll label · 60 × 40 mm · 5,000 pcs · Due Jun 18</span></div>${body}</main>`}
  function renderPortal(key){if(lastPortalKey===key)return;lastPortalKey=key;const layout=$('.portal-layout');if(!layout)return;layout.className='portal-layout v10-layout';
    if(key==='orders')layout.innerHTML=`<main class="portal-home"><div class="portal-home-head"><div><small>ORDER MANAGEMENT</small><h1>Orders</h1><p>Track customer orders, files and collaboration.</p></div><button class="home-new-order" id="homeNewOrder">＋ New Order</button></div><div class="home-order-list"><div><b>ORD-2431</b><span>Sam Fenwick · Kraft label roll</span><small>In collaboration</small></div><div><b>ORD-2435</b><span>Iris Vogel · Folding carton sleeve</span><small>Preparing print files</small></div></div></main>`;
    else if(key==='customer')layout.innerHTML=`<div class="portal-wizard"><h1 class="wizard-title">New Order</h1>${wizardSteps(0)}<div class="wizard-card"><div class="wizard-main"><h2>Customer</h2><p>Find an existing customer by name or email.</p><div class="customer-row"><div class="customer-avatar">EC</div><div><b>Emma Cole</b><br><small>emma@willowandco.example</small></div></div></div>${summaryAside}<div class="wizard-actions"><button>Back</button><button class="primary" id="continueCustomer">Continue to product</button></div></div></div>`;
    else if(key==='product')layout.innerHTML=`<div class="portal-wizard"><h1 class="wizard-title">New Order</h1>${wizardSteps(1)}<div class="wizard-card"><div class="wizard-main"><h2>Choose a product</h2><div class="product-grid"><div class="product-card selected"><span class="product-check">✓</span><img src="assets/willow-label-v1.svg"><b>Roll label</b><small>Kraft / BOPP · 20–120 mm</small></div><div class="product-card"><div class="product-placeholder"></div><b>Business card</b><small>350–400 g</small></div></div></div>${summaryAside}<div class="wizard-actions"><button>Back</button><button class="primary" id="continueProduct">Continue to options</button></div></div></div>`;
    else if(key==='options')layout.innerHTML=`<div class="portal-wizard"><h1 class="wizard-title">New Order</h1>${wizardSteps(2)}<div class="wizard-card"><div class="wizard-main"><h2>Options</h2><div class="option-groups"><div class="option-group"><b>Size</b><div class="option-pills"><span class="option-pill selected">60 × 40 mm</span><span class="option-pill">76 × 51 mm</span></div></div><div class="option-group"><b>Stock</b><div class="option-pills"><span class="option-pill selected">Kraft uncoated</span><span class="option-pill">White BOPP</span></div></div><div class="option-group"><b>Quantity</b><div class="option-pills"><span class="option-pill selected">5,000 pcs</span><span class="option-pill">10,000 pcs</span></div></div></div></div>${summaryAside}<div class="wizard-actions"><button>Back</button><button class="primary" id="continueOptions">Continue to summary</button></div></div></div>`;
    else if(key==='summary')layout.innerHTML=`<div class="portal-wizard"><h1 class="wizard-title">New Order</h1>${wizardSteps(3)}<div class="wizard-card"><div class="wizard-main"><h2>Summary</h2><div class="summary-grid"><div><span>Customer</span><b>Emma Cole</b></div><div><span>Product</span><b>Roll label</b></div><div><span>Variant</span><b>60 × 40 mm · Kraft uncoated</b></div><div><span>Quantity</span><b>5,000 pcs</b></div></div><div class="incoming-assets-summary"><b>Customer files</b><span>3 source assets will be attached to the order</span></div></div>${summaryAside}<div class="wizard-actions"><button>Back</button><button class="primary" id="createDraft">Create order as Draft</button></div></div></div>`;
    else if(key==='draft')layout.innerHTML=portalShell('Roll label · 60 × 40 mm',`<div class="v10-statusline"><span class="pill waiting">Draft</span><span>No design version yet</span></div><div class="v10-columns"><section>${sourceAssets()}</section><section class="v10-card"><h3>Share order</h3><p>Send the customer a secure link to review this order.</p><div class="copy-link-row"><code>collaborative-order.local/o/ORD-2482</code><button id="copyCustomerLink">Copy link</button></div></section></div>`);
    else if(key==='draft-copied')layout.innerHTML=portalShell('Roll label · 60 × 40 mm',`<div class="v10-statusline"><span class="pill waiting">Draft</span><span>No design version yet</span></div><div class="v10-columns"><section>${sourceAssets()}</section><section class="v10-card"><h3>Share order</h3><p>Secure customer link copied to clipboard.</p><div class="copy-link-row copied"><code>collaborative-order.local/o/ORD-2482</code><button id="copyCustomerLink">✓ Copied</button></div></section></div>`);
    else if(key==='team-share')layout.innerHTML=portalShell('Roll label · 60 × 40 mm',`<div class="v10-statusline"><span class="pill waiting">Draft</span><span>Customer invited · Initial design not started</span></div><div class="v10-columns"><section>${sourceAssets()}</section><section class="v10-card"><h3>Bring in the designer</h3><p>Share the same order context with Nora. Source files, specs and future comments stay attached to ORD-2482.</p><div class="copy-link-row"><code>collaborative-order.local/staff/ORD-2482</code><button id="copyDesignerLink">Copy team link</button></div></section></div>`);
    else if(key==='designer-order')layout.innerHTML=portalShell('Designer workspace',`<div class="v10-statusline"><span class="pill waiting">Initial design needed</span><span>Customer source assets ready</span></div><div class="v10-columns"><section>${sourceAssets()}</section><section class="v10-card"><h3>Next action</h3><p>Create the first design version from the customer brief and reference artwork.</p><button class="v10-primary" id="createInitialVersion">Create initial version</button></section></div>`);
    else if(key==='editor-v1')layout.innerHTML=`<div class="v10-editor"><div class="v10-editor-top"><b>ORD-2482 · Initial design</b><span>Using customer assets</span><button id="publishV1">Publish Version 1</button></div><div class="v10-editor-body"><aside><h3>Source files</h3><span>Willow_Brief.pdf</span><span>Current_Label_Reference.pdf</span><span>Willow_Logo.png</span></aside><main><img src="assets/willow-label-v1.svg"><small>60 × 40 mm · Kraft uncoated</small></main></div></div>`;
    else if(key==='v1-published')layout.innerHTML=portalShell('Roll label · 60 × 40 mm',`<div class="v10-statusline"><span class="pill ready">In collaboration</span><span>Version 1 published by Nora</span></div><div class="v10-columns"><section class="v10-proof"><header><b>Version 1</b><small>Latest</small></header><img src="assets/willow-label-v1.svg"></section><section class="v10-card"><h3>Activity</h3><p><b>Nora:</b> Initial version published.</p><p>Customer can now review the design from the secure order link.</p></section></div>`);
    else if(key==='customer-v1')layout.innerHTML=`<div class="customer-shell"><header><b>Meridian.</b><span>Print &amp; Packaging</span><nav>My orders &nbsp; 🔒 Secure session &nbsp; <b>EC</b></nav></header><main><div class="customer-order-head"><small>ORD-2482 · Roll label</small><h1>Roll label · 60 × 40 mm</h1></div><div class="customer-grid"><section class="proof-card"><header><b>Version 1</b><small>Latest</small></header><img src="assets/willow-label-v1.svg"></section><section class="conversation"><h2>Conversation</h2><div class="conversation-msg"><b>Nora · Designer</b><p>Initial version is ready. Please review it here.</p></div><textarea id="customerFeedback" placeholder="Write a message to Meridian"></textarea><button id="sendFeedback">Send feedback</button></section></div></main></div>`;
    else if(key==='customer-typing')layout.innerHTML=`<div class="customer-shell"><header><b>Meridian.</b><span>Print &amp; Packaging</span><nav>My orders &nbsp; 🔒 Secure session &nbsp; <b>EC</b></nav></header><main><div class="customer-order-head"><small>ORD-2482 · Roll label</small><h1>Roll label · 60 × 40 mm</h1></div><div class="customer-grid"><section class="proof-card"><header><b>Version 1</b><small>Latest</small></header><img src="assets/willow-label-v1.svg"></section><section class="conversation"><h2>Conversation</h2><textarea id="customerFeedback">Please change the text to “No artificial flavors” and use “Organic Sourdough” as the product name.</textarea><button id="sendFeedback">Send feedback</button></section></div></main></div>`;
    else if(key==='feedback')layout.innerHTML=portalShell('Customer feedback received',`<div class="v10-statusline"><span class="pill waiting">Your move</span><span>Feedback on Version 1</span></div><div class="v10-columns"><section class="v10-proof"><header><b>Version 1</b><small>Customer reviewed</small></header><img src="assets/willow-label-v1.svg"></section><section class="v10-card"><h3>Emma Cole</h3><blockquote>Please change the text to “No artificial flavors” and use “Organic Sourdough” as the product name.</blockquote><button class="v10-primary" id="applyFeedback">Open in Editor</button></section></div>`);
    else if(key==='editor-v2')layout.innerHTML=`<div class="v10-editor"><div class="v10-editor-top"><b>ORD-2482 · Revision</b><span>Customer feedback applied</span><button id="publishV2">Publish Version 2</button></div><div class="v10-editor-body"><aside><h3>Feedback</h3><span>✓ No artificial flavors</span><span>✓ Organic Sourdough</span></aside><main><img src="assets/willow-label-v2.svg"><small>60 × 40 mm · Kraft uncoated</small></main></div></div>`;
    else if(key==='customer-v2')layout.innerHTML=`<div class="customer-shell"><header><b>Meridian.</b><span>Print &amp; Packaging</span><nav>My orders &nbsp; 🔒 Secure session &nbsp; <b>EC</b></nav></header><main><div class="customer-order-head"><small>ORD-2482 · Roll label</small><h1>Roll label · 60 × 40 mm</h1></div><div class="customer-grid"><section class="proof-card"><header><b>Version 2</b><small>Latest</small></header><img src="assets/willow-label-v2.svg"></section><section class="conversation"><h2>Ready to confirm</h2><p>Nora updated the design based on your feedback.</p><button class="v10-primary" id="confirmOrder">Confirm Version 2</button></section></div></main></div>`;
    else if(key==='production')layout.innerHTML=portalShell('Roll label · 60 × 40 mm',`<div class="v10-statusline"><span class="pill ready">Confirmed</span><span>Version 2 approved by Emma Cole</span></div><div class="v10-production-ready"><div><h2>Order confirmed</h2><p>The approved version is locked. Production can use Version 2 without asking which file is final.</p></div><div class="v10-production-step"><span>✓ Customer confirmed</span><span>✓ Version 2 locked</span><b>Preparing print files…</b></div></div>`);
  }

  function renderDesignerShareMail(pasted=false,sent=false){const key=`designer-share-${pasted}-${sent}`;if(lastChatKey===key)return;lastChatKey=key;setVisible('designer',true);front(W.designer);$('#designerThread').innerHTML=chatMessage('me','Dana','CSR','I created ORD-2482 with the customer brief, reference label and logo.')+chatMessage('me','Dana','CSR',pasted?'Here is the collaboration link for the order: collaborative-order.local/staff/ORD-2482':'I’ll send you the order link so you can prepare Version 1.')+(sent?chatMessage('them','Nora','Designer','Got it — opening the order now.'):'')}

  function resetVisual(){hideAllWindows();showBrowser(false);film.classList.remove('on');stage.classList.remove('rewinding','climax-hold');$$('.chaos-ping,.clipboard-toast,.paste-hint').forEach(x=>x.remove());$('#fileList').innerHTML='';$('#designerThread').innerHTML='';$('#prepressThread').innerHTML='';$('#directorThread').innerHTML='';lastMailKey=lastFilesKey=lastPortalKey=lastChatKey=lastPingKey='';topZ=80;hideCursor(true)}

  function renderAt(t,seeking=false){t=Math.max(0,Math.min(END,t));const chaos=t<33,rew=t>=33&&t<36.5,happy=t>=36.5;stage.classList.toggle('climax-hold',t>=31.2&&t<33);stage.classList.toggle('rewinding',rew);film.classList.toggle('on',rew);
    if(chaos){showBrowser(false);setVisible('outlook',t>=2);task('tbOutlook',t>=2);setVisible('designer',t>=6);setVisible('explorer',t>=8);setVisible('pdf1',t>=10.5);setVisible('prepress',t>=17);setVisible('pdf2',t>=24.5);setVisible('qa',t>=27);setVisible('production',t>=28.5);setVisible('director',t>=30);task('tbTeams',t>=6);task('tbExplorer',t>=8);task('tbPdf',t>=10.5);if(t>=25.5){ensureMailRows('approval');renderMail(revisionMail,'revision-approval')}else if(t>=13){ensureMailRows('revision');renderMail(revisionMail,'revision')}else{ensureMailRows('initial');renderMail(initialMail,'initial')}renderChaosFiles(t);renderStaffChats(t);renderPings(t)}
    else if(rew){showBrowser(false);hideCursor(true);const rt=33-(t-33)*8.2,ct=Math.max(2,Math.min(32.5,rt));setVisible('outlook',ct>=2);setVisible('designer',ct>=6);setVisible('explorer',ct>=8);setVisible('pdf1',ct>=10.5);setVisible('prepress',ct>=17);setVisible('pdf2',ct>=24.5);setVisible('qa',ct>=27);setVisible('production',ct>=28.5);setVisible('director',ct>=30);if(ct>=25.5){ensureMailRows('approval');renderMail(revisionMail,'rw-approval')}else if(ct>=13){ensureMailRows('revision');renderMail(revisionMail,'rw-revision')}else{ensureMailRows('initial');renderMail(initialMail,'rw-initial')}renderChaosFiles(ct);renderStaffChats(ct);renderPings(ct)}
    else if(happy){setVisible('explorer',false);setVisible('pdf1',false);setVisible('pdf2',false);setVisible('qa',false);setVisible('production',false);setVisible('prepress',false);setVisible('director',false);task('tbExplorer',false);task('tbPdf',false);$$('.chaos-ping').forEach(x=>x.remove());
      if(t<39){showBrowser(false);setVisible('designer',false);setVisible('outlook',true);task('tbOutlook',true);renderMail(initialMail,'happy-initial');ensureMailRows('initial')}
      else if(t<52){setVisible('outlook',false);setVisible('designer',false);task('tbOutlook',false);showBrowser(true);const key=t<40.5?'orders':t<42.7?'customer':t<44.9?'product':t<47.1?'options':t<49.4?'summary':t<51.2?'draft':'draft-copied';renderPortal(key)}
      else if(t<58){showBrowser(false);setVisible('designer',false);setVisible('outlook',true);task('tbOutlook',true);if(t<53.1)renderReplyReady();else if(t<54.8)renderReplyComposer(false,false);else if(t<57.2)renderReplyComposer(true,false);else renderReplyComposer(true,true)}
      else if(t<61){setVisible('outlook',false);setVisible('designer',false);task('tbOutlook',false);showBrowser(true);renderPortal('team-share')}
      else if(t<65){showBrowser(false);setVisible('outlook',false);task('tbTeams',true);renderDesignerShareMail(t>=62.3,t>=63.8)}
      else if(t<70){setVisible('designer',false);task('tbTeams',false);showBrowser(true);renderPortal(t<67.2?'designer-order':'editor-v1')}
      else if(t<73){showBrowser(true);renderPortal('v1-published')}
      else if(t<77.5){showBrowser(true);renderPortal(t<74.8?'customer-v1':'customer-typing')}
      else if(t<81){showBrowser(true);renderPortal(t<79?'feedback':'editor-v2')}
      else if(t<84){showBrowser(true);renderPortal('customer-v2')}
      else{showBrowser(true);renderPortal('production')}
    }
    timeEl.textContent=`${t.toFixed(1)} / ${END.toFixed(1)}`;scrubber.value=Math.round(t*100);if(seeking)hideCursor(true)
  }

  function localCenter(sel){const el=typeof sel==='string'?$(sel):sel;if(!el||!el.getClientRects().length)return null;const r=el.getBoundingClientRect(),s=stage.getBoundingClientRect(),scale=s.width/1920;return{x:(r.left+r.width/2-s.left)/scale,y:(r.top+r.height/2-s.top)/scale,el}}
  function setCursorXY(x,y,animate=true){clearTimeout(cursorHideTimer);if(cursorAnim){try{cursorAnim.cancel()}catch(e){}}const wasVisible=getComputedStyle(cursor).opacity!=='0';const to=`translate3d(${x}px,${y}px,0)`;if(!wasVisible)cursor.style.transform=`translate3d(${x-54}px,${y+34}px,0)`;cursor.style.opacity=1;if(!animate){cursor.style.transform=to;return}const from=cursor.style.transform||to;cursorAnim=cursor.animate([{transform:from},{transform:to}],{duration:360/speed,easing:'cubic-bezier(.2,.75,.2,1)',fill:'forwards'});cursorAnim.onfinish=()=>{cursor.style.transform=to;cursorAnim=null}}
  function hideCursor(immediate=false){clearTimeout(cursorHideTimer);if(immediate){cursor.style.opacity=0;return}cursorHideTimer=setTimeout(()=>cursor.style.opacity=0,650/speed)}
  function clickTarget(sel){const p=localCenter(sel);if(!p){hideCursor(true);return false}setCursorXY(p.x,p.y,true);setTimeout(()=>{ring.classList.remove('go');void ring.offsetWidth;ring.style.left=p.x+'px';ring.style.top=p.y+'px';ring.classList.add('go');cursor.classList.remove('press');void cursor.offsetWidth;cursor.classList.add('press');p.el.classList.add('flash','portal-flash');setTimeout(()=>p.el.classList.remove('flash','portal-flash'),340/speed);setTimeout(()=>cursor.classList.remove('press'),240/speed);hideCursor(false)},380/speed);return true}
  function clipboardToast(text){$$('.clipboard-toast').forEach(x=>x.remove());const d=document.createElement('div');d.className='clipboard-toast';d.innerHTML=`<b>📋 ${text}</b><small>Saved to clipboard</small>`;stage.appendChild(d);setTimeout(()=>d.classList.add('show'),20);setTimeout(()=>d.remove(),1500/speed)}
  function pasteHint(sel){const p=localCenter(sel);if(!p)return;const d=document.createElement('div');d.className='paste-hint';d.style.left=(p.x+40)+'px';d.style.top=(p.y-55)+'px';d.textContent='Ctrl + V';stage.appendChild(d);setTimeout(()=>d.classList.add('show'),20);setTimeout(()=>d.remove(),850/speed)}

  const actions=[[2.15,'[data-mail="initial"]','click'],[6.15,'#tbTeams','click'],[8.15,'#tbExplorer','click'],[10.15,'#f-ref','click'],[13.15,'#mail-revision','click'],[21.7,'#f-final','click'],[24.65,'#f-approved2','click'],[36.9,'[data-mail="initial"]','click'],[39.35,'#tbBrowser','click'],[40.05,'#newOrderBtn','click'],[42.25,'#continueCustomer','click'],[44.45,'#continueProduct','click'],[46.65,'#continueOptions','click'],[48.95,'#createDraft','click'],[50.75,'#copyCustomerLink','copyCustomer'],[52.65,'#replyButton','click'],[54.15,'#clientPasteZone','pasteClient'],[56.75,'#sendReply','click'],[59.3,'#copyDesignerLink','copyDesigner'],[61.55,'#designerThread','pasteDesigner'],[63.35,'#designerThread','click'],[65.55,'#createInitialVersion','click'],[69.25,'#publishV1','click'],[74.15,'#customerFeedback','click'],[76.95,'#sendFeedback','click'],[78.55,'#applyFeedback','click'],[80.55,'#publishV2','click'],[83.25,'#confirmOrder','click']];
  function fireAction(idx,sel,type){if(firedActions.has(idx))return;firedActions.add(idx);if(type==='click')clickTarget(sel);else if(type==='copyCustomer'){clickTarget(sel);setTimeout(()=>clipboardToast('Customer order link copied'),500/speed)}else if(type==='copyDesigner'){clickTarget(sel);setTimeout(()=>clipboardToast('Team collaboration link copied'),500/speed)}else if(type==='pasteClient'){clickTarget(sel);setTimeout(()=>pasteHint(sel),420/speed)}else if(type==='pasteDesigner'){clickTarget(sel);setTimeout(()=>pasteHint(sel),420/speed)}}
  function fireCrossedActions(from,to){if(to<=from)return;actions.forEach((a,i)=>{if(a[0]>from&&a[0]<=to)fireAction(i,a[1],a[2])})}

  function tick(now){if(!playing)return;const t=Math.min(END,base+(now-startPerf)/1000*speed);renderAt(t,false);fireCrossedActions(lastT,t);lastT=t;if(t>=END){playing=false;hideCursor(false);return}raf=requestAnimationFrame(tick)}
  function play(){if(playing)return;playing=true;startPerf=performance.now();lastT=base;raf=requestAnimationFrame(tick)}
  function pause(){if(!playing)return;const now=performance.now();base=Math.min(END,base+(now-startPerf)/1000*speed);playing=false;cancelAnimationFrame(raf);lastT=base;renderAt(base,true)}
  function seek(t){playing=false;cancelAnimationFrame(raf);base=Math.max(0,Math.min(END,t));lastT=base;firedActions.clear();actions.forEach((a,i)=>{if(a[0]<=base)firedActions.add(i)});renderAt(base,true)}
  function restart(){playing=false;cancelAnimationFrame(raf);resetVisual();base=0;lastT=0;firedActions.clear();renderAt(0,true)}
  $('#play').onclick=play;$('#pause').onclick=pause;$('#restart').onclick=restart;$('#speed').onclick=()=>{speed=speed===1?1.5:speed===1.5?.75:1;$('#speed').textContent=speed+'×'};scrubber.addEventListener('input',()=>seek(Number(scrubber.value)/100));$$('[data-snap]').forEach(b=>b.onclick=()=>{const map={clean:0,initial:3,peak:31.5,product:49.8};seek(map[b.dataset.snap]??0)});addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();playing?pause():play()}if(e.key.toLowerCase()==='r')restart();if(e.key==='ArrowLeft')seek(base-1);if(e.key==='ArrowRight')seek(base+1)});
  restart();if(params.get('autoplay')==='1'||params.get('record')==='1')setTimeout(play,500);
})();
