const DURATION=78;
const $=s=>document.querySelector(s);
const all=s=>[...document.querySelectorAll(s)];
const cursor=$('#cursor'), scrubber=$('#scrubber'), readout=$('#timeReadout');
let startAt=0, pausedAt=0, playing=false, raf=null, lastT=-1;
function show(sel,on=true){const e=$(sel);if(!e)return;e.classList.toggle('hidden',!on)}
function scene(id){all('.scene').forEach(e=>e.classList.remove('active','flip-out-left','flip-in-right'));$('#'+id).classList.add('active')}
function moveCursor(x,y,click=false){show('#cursor',true);cursor.style.left=x+'px';cursor.style.top=y+'px';if(click){cursor.classList.remove('click');void cursor.offsetWidth;cursor.classList.add('click')}}
function fmt(t){const m=Math.floor(t/60),s=(t%60).toFixed(1).padStart(4,'0');return `${m}:${s}`}
function resetVisual(){scene('desktop');show('#cursor',false);show('#rewind',false);['#teams','#explorer','#pdf','#reply1','#reply2','#reply3','#prepressToast'].forEach(s=>show(s,false));all('.msg').forEach((e,i)=>{if(i>0)e.classList.remove('show')});all('.folder-row').forEach((e,i)=>{if(i>0)e.classList.remove('show')});show('#sellerCreate',true);show('#sellerOrder',false);$('#sellerTitle').textContent='New Order';show('#customerSaved',false);show('#histV2',false);show('#histConfirmed',false);show('#employeeConfirm',false);show('#submitted',false);show('#pipelineState',false);show('#readyState',false);$('#versionTag').textContent='Version 1';$('#sellerArtwork').src='./assets/willow-label-v1.png';show('#mobileOrder',true);show('#mobileEditor',false);show('#mobileConfirmed',false);show('#confirmBtn',false);$('#mobileArtwork').src='./assets/willow-label-v1.png';$('#editorArtwork').src='./assets/willow-label-v1.png';$('#mobileVersion').textContent='Current design · Version 1';$('#copyField').value='Made with simple ingredients';$('#claimField').value='';show('#editSelection',false);$('#inviteBtn').textContent='Invite customer';$('#inviteBtn').style.background=''}
function apply(t){if(t<lastT||t<.1)resetVisual();lastT=t;if(t<15){scene('desktop');show('#rewind',false);if(t>1.2)moveCursor(520,210);if(t>4.2){show('#teams',true);moveCursor(1460,320,true)}if(t>6.3)all('.msg')[1]?.classList.add('show');if(t>7.8){show('#reply1',true);moveCursor(1650,120)}if(t>9.0)show('#reply2',true);if(t>9.8){show('#explorer',true);all('.folder-row')[1]?.classList.add('show')}if(t>10.8){all('.folder-row')[2]?.classList.add('show');show('#pdf',true)}if(t>11.7){all('.folder-row')[3]?.classList.add('show');all('.msg')[2]?.classList.add('show');show('#prepressToast',true)}if(t>12.7)all('.folder-row')[4]?.classList.add('show');if(t>13.5){all('.folder-row')[5]?.classList.add('show');show('#reply3',true);moveCursor(1050,650)}}if(t>=15&&t<18){scene('desktop');show('#rewind',true);show('#cursor',false)}if(t>=18&&t<30){show('#rewind',false);scene('seller');if(t<23){show('#sellerCreate',true);show('#sellerOrder',false);moveCursor(1640,790)}if(t>=23){show('#sellerCreate',false);show('#sellerOrder',true);$('#sellerTitle').textContent='ORD-2482';moveCursor(1640,175,t<24)}if(t>=26){$('#inviteBtn').textContent='Customer invited ✓';$('#inviteBtn').style.background='#17a673'}}if(t>=30&&t<39){scene('customer');show('#mobileOrder',true);show('#mobileEditor',false);show('#mobileConfirmed',false);moveCursor(1125,760)}if(t>=39&&t<49){scene('customer');show('#mobileOrder',false);show('#mobileEditor',true);show('#mobileConfirmed',false);if(t>40.5){show('#editSelection',true);$('#copyField').value='No artificial flavors';$('#claimField').value='Sourdough Boule'}if(t>44){$('#editorArtwork').src='./assets/willow-label-v2.png';moveCursor(1120,180)}}if(t>=49&&t<57){scene('seller');show('#sellerCreate',false);show('#sellerOrder',true);$('#sellerTitle').textContent='ORD-2482';$('#versionTag').textContent='Version 2';$('#sellerArtwork').src='./assets/willow-label-v2.png';show('#customerSaved',true);show('#histV2',true);moveCursor(1330,490)}if(t>=57&&t<65){scene('customer');$('#mobileArtwork').src='./assets/willow-label-v2.png';$('#mobileVersion').textContent='Current design · Version 2';show('#mobileEditor',false);if(t<61){show('#mobileOrder',true);show('#mobileConfirmed',false);show('#confirmBtn',true);moveCursor(1110,810,t>60)}else{show('#mobileOrder',false);show('#mobileConfirmed',true)}}if(t>=65&&t<74){scene('seller');show('#sellerOrder',true);$('#versionTag').textContent='Version 2';$('#sellerArtwork').src='./assets/willow-label-v2.png';show('#customerSaved',true);show('#histV2',true);show('#histConfirmed',true);if(t<68){show('#employeeConfirm',true);moveCursor(1580,850,t>67)}else{show('#employeeConfirm',false);show('#submitted',true)}if(t>=70){show('#submitted',false);show('#pipelineState',true);moveCursor(1610,850,t<70.8)}if(t>=72.5){show('#pipelineState',false);show('#readyState',true)}}if(t>=74){scene('packshot');show('#cursor',false)}readout.textContent=`${fmt(t)} / 1:18.0`;scrubber.value=t}
function tick(now){if(!playing)return;const t=Math.min(DURATION,(now-startAt)/1000);apply(t);if(t>=DURATION){playing=false;cancelAnimationFrame(raf);return}raf=requestAnimationFrame(tick)}
function play(){if(playing)return;playing=true;startAt=performance.now()-pausedAt*1000;raf=requestAnimationFrame(tick)}
function pause(){if(!playing)return;playing=false;pausedAt=(performance.now()-startAt)/1000;cancelAnimationFrame(raf)}
function restart(){playing=false;pausedAt=0;lastT=-1;resetVisual();apply(0);play()}
$('#playBtn').onclick=play;$('#pauseBtn').onclick=pause;$('#restartBtn').onclick=restart;scrubber.oninput=e=>{pause();pausedAt=+e.target.value;lastT=-1;apply(pausedAt)};document.addEventListener('keydown',e=>{if(e.key.toLowerCase()==='h')$('#devControls').classList.toggle('hidden');if(e.code==='Space'){e.preventDefault();playing?pause():play()}if(e.key==='r')restart()});$('#createOrderBtn').onclick=()=>{show('#sellerCreate',false);show('#sellerOrder',true);$('#sellerTitle').textContent='ORD-2482'};$('#editBtn').onclick=()=>{show('#mobileOrder',false);show('#mobileEditor',true)};$('#backOrder').onclick=()=>{show('#mobileEditor',false);show('#mobileOrder',true)};$('#saveBtn').onclick=()=>{$('#editorArtwork').src='./assets/willow-label-v2.png';$('#mobileArtwork').src='./assets/willow-label-v2.png';show('#mobileEditor',false);show('#mobileOrder',true);show('#confirmBtn',true);$('#mobileVersion').textContent='Current design · Version 2'};$('#confirmBtn').onclick=()=>{show('#mobileOrder',false);show('#mobileConfirmed',true)};resetVisual();apply(0);